# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven (JDK 8)

on:
  push:
    branches: [ maint-0.9 ]
  pull_request:
    branches: [ maint-0.9 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'      
        java-version: '8'
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B verify checkstyle:checkstyle --file pom.xml
    - name: Upload jar artifact
      uses: actions/upload-artifact@v2
      with:
        name: ukf-mda-snapshot
        path: target/ukf-mda*.jar
